# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Dooz"
license = "MIT"
licenselink = "https://github.com/hollson/hugo-theme-dooz/blob/master/LICENSE"
description = "Dooz is a simple and elegant hugo theme specially designed for programmers or columnists."
homepage = "http://www.mafool.com/"
tags = ["blog","tech"]
min_version = "0.41"

[author]
  name = "hollson"
  homepage = "http://www.mafool.com/"
