# 全局设置
baseURL = "http://www.mafool.com"
title = "码夫庄园"
theme = "hugo-theme-dooz"
languageCode = "en"
defaultContentLanguage = "en"  #调整中英文
hasCJKLanguage = true
enableEmoji= true
copyright="版权所有"
googleAnalytics = "G-DK042XSJ2J" #内置了谷歌统计模板  {{ template "_internal/google_analytics_async.html" . }}

canonifyurls = true
paginate = 10
metaDataFormat = "toml"

[languages]
  [languages.zh]
    # baseURL = "http://www.mafool.com"
    languagedirection = "zh"
    title = "码夫庄园"
    languageName = "Chinese"
    weight = 1
  [languages.en]
    # baseURL = "https://hollson.github.io"
    # contentDir = "content/english"
    title = "Mafool"
    languageName = "English"
    copyright="All Rights Reserved"
    weight = 1
    [languages.en.params]
      #author= "shongsheng" #replace the dedault param
      homeTitle="Programmer's Exclusive Blog" 
      slogan="A Hugo theme for programmers."
      title_404="Sorry, page was not found."

[outputs]
#home = ["HTML", "RSS"]
home = ["HTML", "RSS", "JSON"]

# 首页设置
[params]
  #Author
  author = "sybs"
  city = "Beijing"
  avatar = "img/my/avatar.png"
  aphorism="Your attitude determines your life"
  github="https://github.com/xxx"
  csdn="https://blog.csdn.net/xxx"
  cnblog="https://www.cnblogs.com/xxx/"

  #打赏功能 
  reward= true
  rewardTitle="真诚赞赏，手留余香"
  rewardPrompt="嗯，我的梦想是被读者的稿费包养~"


  #公告信息(支持markdown语法)
  notice="**[Dooz theme](https://github.com/hollson/hugo-theme-dooz)** updated, hurry up and experience it! `2020.03.22`"
 
  #站点设置
  timeOfMonth="2006年1月"
  timeOfDay="2006年1月2日"
  hero = "img/res/hero.jpg"
  slogan = "提升码农亩产，掰直码农方向，授人以渔，功德无量，利在千秋 。"
  image_404 = "img/res/404.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  openShare= true
  
  #百度统计
  analyze_baidu="f185359ec6b829a6a93e1e1f2597f6d9"  #Mafool
  # analyze_baidu_gitee="d4c707fc3a17c53bb106bb52238032f0"   #Gitee
  analyze_google="G-DK042XSJ2J"

  #SEO优化(meta中的信息)
  homeTitle = "码农的专属博客"
  keywords = "码农,hugo,theme,blog,developer,programmer,coder,geek,程序员,主题,个人博客,github博客,golang,微服务"
  description = "码夫庄园是一个使用hugo搭建的程序员专属博客站点，以优美的博客风格，丰富的展现方式向广大程序员们传播最新的golang、docker、k8s、微服务、大数据、人工智能、等技术。"

# 友情链接
# https://gohugo.io/documentation/

[permalinks]
    post = "/:year/:month/:title"

# 分类体系（Taxonomies）表示作者对内容的一套或多套分类。比如标签（tags）、类目（categories）、归档（archives）等
[taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archives"
    # series = "series"

# 页脚导航菜单
[[menu.friendly]]
    name="Mafool"
    url="http://www.mafool.com"
    weight="1"
[[menu.friendly]]
    name="Hugo"
    url="https://gohugo.io/documentation/"
    weight="2"
[[menu.friendly]]
    name="Bulma"
    url="https://bulma.io/"
    weight="3"
[[menu.friendly]]
    name="Bootstrapious"
    url="https://bootstrapious.com/"
    weight="4"
[[menu.friendly]]
    name="Youzhixueyuan"
    url="https://youzhixueyuan.com/"
    weight="5"

#https://gohugo.io/getting-started/configuration-markup#highlight markdown配置
#https://gohugo.io/content-management/shortcodes/#highlight  短码
#https://gohugo.io/content-management/syntax-highlighting/ 高亮
[markup]
  defaultMarkdownHandler = "goldmark" #默认的Markdown渲染器
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = false
      xHTML = false
  [markup.highlight]      #Hugo使用Chroma作为其代码突出显示器
    codeFences = true     #代码栅栏
    guessSyntax = true    #猜测
    lineNoStart = 1       #行号初始值
    lineNos = true        #显示行号
    lineNumbersInTable = true
    style = "monokai"     #代码风格，参考https://xyproto.github.io/splash/docs/longer/all.html
    tabWidth = 8
  [markup.tableOfContents] #文档目录，H1作为SEO的关键字
    startLevel = 2         #开始级别：H2
    endLevel = 3           #结束级别：H3
    ordered = false        #是否排序